---
# Install the necessary packages
- name: Install package requirements for bookstack
  apt:
    name:
      - git
      - unzip
      - apache2
      - php8.1
      - curl
      - php8.1-curl
      - php8.1-mbstring
      - php8.1-ldap
      - php8.1-xml
      - php8.1-zip
      - php8.1-gd
      - php8.1-mysql
      - mysql-server-8.0
      - libapache2-mod-php8.1
      - composer
    update_cache: yes

# Clone the bookstack repository
# To be completed
- name: Clone BookStack repository
  git:
    repo: https://github.com/BookStackApp/BookStack.git
    dest: /var/www
    version: bookstack
    depth: 1
    single_branch: true

# Install the bookstack dependencies with Composer.
# To be completed
- name: Install BookStack Composer dependencies
    php /usr/bin/composer install --no-dev --no-plugins
  shell: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php --quiet
    rm composer-setup.php
    mv composer.phar /usr/local/bin/composer
    cd "$BOOKSTACK_DIR" || exit
    export COMPOSER_ALLOW_SUPERUSER=1
    php /usr/local/bin/composer install --no-dev --no-plugins

# Create .env file from template
# To be completed
- name: create .env file from template
  template:
    dest: /var/www/bookstack/.env
    src: /bookstack_templates/env.j2

# Generate application key
- name: generate application key
  shell: |
    cd {{ BOOKSTACK_DIR }}
    php artisan key:generate --no-interaction --force
    php artisan migrate --no-interaction --force

# Change file permissions in bookstack directory
- name: change permissions
  shell: |
    cd {{ BOOKSTACK_DIR }}
    chown -R root:www-data ./
    chmod -R 755 ./
    chmod -R 775 bootstrap/cache public/uploads storage
    git config core.fileMode false

# Enable apache modules
# To be completed
- name: enable apache modules
  shell: a2enmod rewrite
    a2enmod php8.1

# Create apache config file from template
# To be completed
- name: create apache config
  template:
    dest: /etc/apache2/sites-available/bookstack.conf
    src: /bookstack_templates/bookstack.conf.j2

# Enable the bookstack apache config
- name: disable default apache config and enable bookstack conf
  shell: |
    a2dissite 000-default.conf
    a2ensite bookstack.conf

# Restart apache service
# To be completed
- name: restart nginx
  service:
    name: nginx
    state: restarted
