---
# Role to setup the database server
- name: Roles for the database servers
  hosts: tag_Name_ubuntu_web
  remote_user: ubuntu
  become: true
  roles:
    - database
    - bookstack
# Role to setup the bookstack server
# to be completed
# Use a tag to target the appropriate ec2 instance
